=== mikaelsvensson/photoorganizer-core/resources/database/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://photoorganizer.info/database" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:po="http://photoorganizer.info/database">

    
    
    <complexType name="IntegerNumberTag">
    	<complexContent>
    		<extension base="po:ValueTag">
    			<attribute name="value" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="IntegerNumberTagDefinition">
    	<complexContent>
    		<extension base="po:ValueTagDefinition"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="KeywordTag">
    	<complexContent>
    		<extension base="po:Tag"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="KeywordTagDefinition">
    	<complexContent>
    		<extension base="po:TagDefinition">
    			<sequence>
    				<element name="KeywordTagDefinition"
    					type="po:KeywordTagDefinition" maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>
    			<attribute name="synonyms" type="IDREFS"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="RealNumberTag">
    	<complexContent>
    		<extension base="po:ValueTag">
    			<attribute name="value" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="RealNumberTagDefinition">
    	<complexContent>
    		<extension base="po:ValueTagDefinition"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Tag" abstract="true">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="tagdefinition" type="IDREF"></attribute>
    			<attribute name="region" type="string"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="TagDefinition" abstract="true">
    	<complexContent>
    		<extension base="po:DatabaseObject">
    			<attribute name="name" type="string" use="required"></attribute>
    			<attribute name="applicabletophotoregion" type="boolean"
    				use="optional">
    			</attribute>
    			<attribute name="isuserallowedtoedittags" type="boolean"></attribute>
    			<attribute name="isuserallowedtocreatetags" type="boolean"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TextTag">
    	<complexContent>
    		<extension base="po:ValueTag">
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TextTagDefinition">
    	<complexContent>
    		<extension base="po:ValueTagDefinition"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="ValueTag" abstract="true">
    	<complexContent>
    		<extension base="po:Tag"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="ValueTagDefinition">
    	<complexContent>
    		<extension base="po:TagDefinition"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Database">
    	<complexContent>
    		<extension base="po:DatabaseObject">
    			<sequence maxOccurs="unbounded" minOccurs="0">

                    <choice><element name="IndexingConfigurations" type="po:IndexingConfigurations" maxOccurs="1" minOccurs="0">
    				</element><element name="Photos" type="po:Photos" maxOccurs="1" minOccurs="0">
    				</element><element name="TagDefinitions" type="po:TagDefinitions" maxOccurs="1" minOccurs="0">
    				</element></choice>
    			</sequence>
    			<attribute name="name" type="string" use="optional"></attribute>
    		</extension>
    	</complexContent>
    </complexType>


    <complexType name="DatabaseObject">
    	<attribute name="id" type="ID"></attribute>
    </complexType>

    <complexType name="Photo">
    	<complexContent>
    		<extension base="po:DatabaseObject">
    			<sequence maxOccurs="unbounded" minOccurs="0">
                    <choice>
                    	<element name="KeywordTag"
                    		type="po:KeywordTag">
                    	</element>
                    	<element name="RealNumberTag"
                    		type="po:RealNumberTag">
                    	</element>
                    	<element name="IntegerNumberTag"
                    		type="po:IntegerNumberTag">
                    	</element>
                    	<element name="TextTag" type="po:TextTag"></element>
                    	<element name="RationalNumberTag"
                    		type="po:RationalNumberTag">
                    	</element>
                    	<element name="DatetimeTag" type="po:DatetimeTag"></element>
                    </choice>
    			</sequence>
    			<attribute name="uri" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <element name="Database" type="po:Database"></element>






    <complexType name="Photos">
    	<sequence>
    		<element name="Photo" type="po:Photo" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TagDefinitions">
    	<sequence maxOccurs="unbounded" minOccurs="0">
    		<choice>
    			<element name="KeywordTagDefinition"
    				type="po:KeywordTagDefinition">
    			</element>
    			<element name="IntegerNumberTagDefinition"
    				type="po:IntegerNumberTagDefinition">
    			</element>
    			<element name="RealNumberTagDefinition"
    				type="po:RealNumberTagDefinition">
    			</element>
    			<element name="TextTagDefinition"
    				type="po:TextTagDefinition">
    			</element>
    			<element name="RationalNumberTagDefinition"
    				type="po:RationalNumberTagDefinition">
    			</element>
    			<element name="DatetimeTagDefinition" type="po:DatetimeTagDefinition"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="RationalNumberTag">
    	<simpleContent>
    		<extension base="po:ValueTag">
    			<attribute name="numerator" type="long"></attribute>
    			<attribute name="denominator" type="long"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="RationalNumberTagDefinition">
    	<complexContent>
    		<extension base="po:ValueTagDefinition"></extension>
    	</complexContent>
    </complexType>

    <complexType name="DatetimeTag">
    	<simpleContent>
    		<extension base="po:ValueTag">
    			<attribute name="value" type="dateTime"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
    
    <complexType name="DatetimeTagDefinition">
    	<complexContent>
    		<extension base="po:ValueTagDefinition"></extension>
    	</complexContent>
    </complexType>


    <complexType name="MultiParameterFunction">
    	<sequence>
    		<element name="Parameter" type="po:Parameter" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="Parameter">
		<attribute name="name" type="string" use="optional"></attribute>
		<attribute name="value" type="string"></attribute>
    </complexType>
    
    <complexType name="IndexingConfigurations">
    	<sequence>
    		<element name="IndexingConfiguration" type="po:IndexingConfiguration" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="IndexingConfiguration">
    	<complexContent>
    		<extension base="po:DatabaseObject">
    			<sequence>
    				<element name="KeywordTranslatorFileFilter"
    					type="po:SingleParameterFunction" maxOccurs="1"
    					minOccurs="0">
    				</element>
    				<element name="MetadataMappingConfigurations" type="po:MetadataMappingConfigurations" maxOccurs="1" minOccurs="0"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="SingleParameterFunction">
    	<attribute name="param" type="string"></attribute>
    </complexType>

    <complexType name="MetadataMappingConfiguration">
    	<sequence maxOccurs="unbounded" minOccurs="0">
    		<choice>
    			<element name="TextCaseTransformer"
    				type="po:SingleParameterFunction">
    			</element>
    			<element name="ReplaceTransformer"
    				type="po:MultiParameterFunction">
    			</element>
    		</choice>
    	</sequence>
    	<attribute name="source" type="string"></attribute>
    	<attribute name="target" type="IDREF"></attribute>
    </complexType>

    <complexType name="MetadataMappingConfigurations">
    	<sequence>
    		<element name="MetadataMappingConfiguration" type="po:MetadataMappingConfiguration" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== mikaelsvensson/photoorganizer-core/resources/database/xml/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Database xmlns="http://photoorganizer.info/database"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://photoorganizer.info/database schema.xsd ">
	<TagDefinitions>
		<RealNumberTagDefinition id="id-36d86990-728a-4b3d-ab6c-ab6daadb7d3e"
			name="aperture" />
		<TextTagDefinition id="id-1622289b-f013-4243-960d-110b4da681c6"
			name="camera" />
		<TextTagDefinition id="id-646e958d-1d34-4d4d-be88-40f1680c6005"
			name="comment" />
		<TextTagDefinition id="id-ee43022f-aa37-4b29-b5a2-27d07aa388a5"
			name="date taken" />
		<IntegerNumberTagDefinition id="id-26be7a9d-1ef8-4d5c-b32b-2258cf761a8b"
			name="rating" />
		<RealNumberTagDefinition id="id-e54d8495-81b9-48b4-a106-0f8d6d4780ca"
			name="shutter speed" />
		<KeywordTagDefinition id="id-f4840997-b116-43e6-8256-6fbaefb63b3d"
			name="root keyword" />
		<KeywordTagDefinition id="id-ab014f5b-3ac7-484d-8604-444606e56bde"
			name="People" />
		<KeywordTagDefinition id="id-697391ab-ca2c-4082-8efa-db9dbbde36bf"
			name="Locations" />
		<KeywordTagDefinition id="id-d9ec96c6-3800-4d3a-91dc-e23f33e5b862"
			name="Objects" />
		<KeywordTagDefinition id="id-efdae686-cfaa-41b4-ad6e-8578a007f8d9"
			name="John F Kennedy" synonyms="id-7322ee08-1ebe-4d74-91a4-41210722c8bc" />
		<KeywordTagDefinition id="id-7322ee08-1ebe-4d74-91a4-41210722c8bc"
			name="JKF" synonyms="id-efdae686-cfaa-41b4-ad6e-8578a007f8d9" />
	</TagDefinitions>
	<Photos>
		<Photo uri="http://demo/test.jpg">
			<KeywordTag tagdefinition="id-d9ec96c6-3800-4d3a-91dc-e23f33e5b862" />
			<TextTag tagdefinition="id-646e958d-1d34-4d4d-be88-40f1680c6005">a flower</TextTag>
		</Photo>
	</Photos>
</Database>
